services:
  django:
    container_name: django_api_server
    image: matt5816/django-api-server:latest
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5000:8000"
    networks:
      - mysql-db
  db:
    container_name: mysql
    image: database:latest
    build: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - mysql-db

volumes:
  db-vol:

networks:
  mysql-db: