services:
  laravel:
    container_name: laravel_api_server
    image: matt5816/laravel-api-server:latest
    environment:
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "80:80"
    networks:
      - mysql-db
  db:
    container_name: mysql
    image: "matt5816/api-servers-comparison-database:latest"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - mysql-db

networks:
  mysql-db: