services:
  spring:
    container_name: spring_api_server
    image: matt5816/spring-api-server:latest
    environment:
      db_host: db
      db_name: ${MYSQL_DATABASE}
      db_user: ${MYSQL_USER}
      db_password: ${MYSQL_PASSWORD}
      jwt_secret: ${JAVA_JWT_SECRET}
    ports:
      - "80:8080"
    networks:
      - mysql-db
  db:
    container_name: mysql
    image: "matt5816/api-servers-comparison-database:latest"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - mysql-db

networks:
  mysql-db: